version: '3'
services:
  app:
    build: .
    ports:
      - "80:3000"
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
